#!/usr/bin/env bash
# .harness/init.sh — standard project init (regenerated by /harness-bootstrap)
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
echo "[1/3] pnpm install"
pnpm install
echo "[2/3] pnpm --filter worker test"
pnpm --filter worker test
echo "[3/3] ready. dev: pnpm --filter worker dev (worker) + pnpm --filter web dev (web)"
